version: 0.1

phases:
  install:
    commands:
      - cd functions
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - boot build
artifacts:
  files:
    - target/main.js
    - index.js
