version: 0.1

phases:
  install:
    commands:
      - cd functions && npm install
  build:
    commands:
      - echo Build started on `date`
      - cd functions && boot build
artifacts:
  files:
    - functions/target/main.js
    - functions/index.js
