ResourcesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
    - AttributeName: resource-url
      AttributeType: S
    KeySchema:
    - AttributeName: resource-url
      KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: '1'
      WriteCapacityUnits: '1'
    StreamSpecification:
      StreamViewType: NEW_IMAGE
    TableName: resources-${opt:stage}

IdentitiesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
    - AttributeName: auth-id
      AttributeType: S
    KeySchema:
    - AttributeName: auth-id
      KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: '1'
      WriteCapacityUnits: '1'
    StreamSpecification:
      StreamViewType: NEW_IMAGE
    TableName: identities-${opt:stage}

ProfilesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
    - AttributeName: user-name
      AttributeType: S
    KeySchema:
    - AttributeName: user-name
      KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: '1'
      WriteCapacityUnits: '1'
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    TableName: profiles-${opt:stage}

BookmarksTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
    - AttributeName: resource-url
      AttributeType: S
    - AttributeName: offcourse-id
      AttributeType: S
    KeySchema:
    - AttributeName: resource-url
      KeyType: HASH
    - AttributeName: offcourse-id
      KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: '1'
      WriteCapacityUnits: '1'
    StreamSpecification:
      StreamViewType: NEW_IMAGE
    TableName: bookmarks-${opt:stage}

CoursesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
    - AttributeName: course-id
      AttributeType: S
    - AttributeName: revision
      AttributeType: N
    KeySchema:
    - AttributeName: course-id
      KeyType: HASH
    - AttributeName: revision
      KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: '1'
      WriteCapacityUnits: '1'
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    TableName: courses-${opt:stage}
